import { Pizza } from "lucide-react";
import { MotionDiv, MotionH3 } from "../common/motion-wrapper";
import SummaryViewer from "@/components/summaries/summary-viewer";
const DEMO_SUMMARY = `
# 🚀 Mastering Advanced JavaScript Concepts for Interviews
• 🎯 Get ready to ace your JavaScript interview with these advanced concepts!

# Document Details
• 📄 Type: Guide
• 👥 For: Aspiring JavaScript Developers

# Key Highlights
• 🚀 Understand Callbacks: Functions executed after another function finishes. 
• ⭐️ Dive into Promises: Objects for handling asynchronous operations. 
• 💫 Explore Async/Await: Simplifying promise handling in your code.

# Why It Matters
• 💡 Mastering these advanced concepts not only boosts your coding skills but also prepares you for technical interviews, helping you stand out in the tech industry.

# Main Points
• 🎯 Callbacks can lead to "callback hell" if not managed well. 
• 💪 Promises offer a cleaner way to handle asynchronous code. 
• 🔥 Async/Await helps you write more readable asynchronous code.

# Pro Tips
• ⭐️ Use "use strict" for cleaner, error-free code. 
• 💎 Leverage higher-order functions like map and filter to streamline your code. 
• 🌟 Implement IIFE for immediate function execution and to avoid global namespace pollution.

# Key Terms to Know
• 📚 Closure: A function with access to its outer function's variables. 
• 🔍 Hoisting: Variables and function declarations are moved to the top of their scope.

# Bottom Line
• 💫 Master these advanced JavaScript concepts to elevate your coding skills and impress in interviews! Remember, there's always more to learn, so keep coding and keep growing! 💻✨
        
Original File: js-interview-questions.pdf
Generated by Sommaire

`;

export default function DemoSection() {
  return (
    <section className="relative">
      <div className="py-12 lg:py-24 max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 lg:pt-12">
        <div
          aria-hidden="true"
          className="pointer-events-none absolute insert-0 -z-10 transform-gpu overflow-hidden blur-3xl"
        >
          <div
            className="relative left-[calc(50%+3rem)] aspect-1155/678 w-[36.125rem] -translate-x-1/2 bg-linear-to-br from-emerald-500 via-teal-500 to-cyan-500 opacity-30 sm:left-[calc(50%+36rem)] sm:w-[72.1875rem]"
            style={{
              clipPath:
                "polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)"
            }}
          />
        </div>
        <div className="flex flex-col items-center space-y-4">
          <div className="inline-flex items-center justify-center p-2 rounded-2xl bg-gray-100/80 backdrop-blur-xs border border-gray-500/20 mb-4">
            <Pizza className="w-6 h-6 text-rose-500" />
          </div>
          <div className="text-center mb-16">
            <MotionH3
              initial={{ y: 20, opacity: 0 }}
              whileInView={{ y: 0, opacity: 1 }}
              transition={{ duration: 0.5, delay: 0.2 }}
              className="font-bold text-3xl max-w-2xl mx-auto px-4 sm:px-6"
            >
              Watch how Sommaire transforms{" "}
              <span className="bg-linear-to-r from-rose-500 to-rose-700 bg-clip-text text-transparent">
                this Next.js app PDF
              </span>{" "}
              into an easy-to-read summary!
            </MotionH3>
          </div>
        </div>
        <div className="flex justify-center items-center px-2 sm:px-4 lg:px-6 min-h-[80vh] w-full">
          {/* Summmary Viewer */}
          <MotionDiv
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            transition={{ duration: 0.5 }}
            className="w-[800px] min-h-[600px] flex items-center justify-center"
          >
            <SummaryViewer summary={DEMO_SUMMARY} />
          </MotionDiv>
        </div>
      </div>
    </section>
  );
}
